### ISSUE TITLE
Muting not working as expected

### ISSUE THREAD

**Issue by techvice** [GUiHKX/spotishush#3]
Seems like another change might have happened. The tab isn't muting or un-muting as it has previously. Gotta love how much they change the website... 

I can't find anyone else reporting the problem however.

**Comment by GUiHKX** [comment]
I'm unable to test it right now because Spotify is [throwing me a bunch of errors](https://i.imgur.com/XB97bNH.png)

Can you please leave the Developer console open while you listen to some music for about 30 to 35 minutes (that's usually the interval you'll start to get audio ads), and then observe the console if some error pops up? Screenshoting the console and posting it here also helps

Thanks

**Comment by techvice** [comment]
Hmm... I didn't have my console open but I just recognized that it worked on this last set of ads... 

I'll open up the console and see if I can spot anything. This may end up being nothing worth looking at.

**Comment by GUiHKX** [comment]
I just tried to reproduce this on both Chromium [(1)](https://i.imgur.com/HYO3LaU.png) and Firefox [(1)](https://i.imgur.com/fvTZoce.png) [(2)](https://i.imgur.com/ztmnRqn.png) on Linux, but in both instances the tab was successfully muted. Anyway, I'll keep an eye on it as well for the next few days

**Comment by techvice** [comment]
It must have been a weird fluke on my machine. If I can get any logs of it reproducing, I'll reopen and add them.
