### ISSUE TITLE
Any chance you could make a Deezershush?

### ISSUE THREAD

**Issue by Dyras** [guihkx/spotishush#4]
Greetings! I've been using this for over a month now, and if you had a Patreon I'd easily donate some money for you every month simply for existing on the same plane of existence as e. I really like this addon and I've started recommending it to all my friends.

With that said, I've gotten interested in using Deezer lately as it donates more money to the artists. Any chance you could release a similar addon for that? 

Deezishush? :)

**Comment by guihkx** [comment]
Thank you for the kind words, I'm really glad you liked it.

I've never used Deezer myself, but I guess I could give it try and create a "sister" addon as well... We'll see. :)

And honestly, I didn't even think about setting up a Patreon page, because I consider my projects just hobby activity. Maybe in the future though, who knows.

**Comment by guihkx** [comment]
Experimental support for Deezer has been added in the last version, so please update your extension if you want to test it out... :)

I thought a lot about it and decided to not create a separate extension just for Deezer. Since the code base of the two are very similar (plus the code for Deezer being way to simple to implement), it wouldn't make much sense to maintain two separate repositories.

Let me know if you encounter any issue.
